import { Test, TestingModule } from '@nestjs/testing';
import { AddonsService } from './addons.service';
import { PrismaService } from '../../prisma/prisma.service';

// Minimal smoke spec generated by the Nest CLI. The placeholder version omitted
// PrismaService and crashed Nest's DI on every CI run; supplying an empty
// provider here is enough to satisfy the container without pulling in a real DB.
describe('AddonsService', () => {
  let service: AddonsService;

  beforeEach(async () => {
    const module: TestingModule = await Test.createTestingModule({
      providers: [
        AddonsService,
        { provide: PrismaService, useValue: {} },
      ],
    }).compile();

    service = module.get<AddonsService>(AddonsService);
  });

  it('should be defined', () => {
    expect(service).toBeDefined();
  });
});
