import { Test, TestingModule } from '@nestjs/testing';
import { AddonsController } from './addons.controller';
import { AddonsService } from './addons.service';

// Minimal smoke spec generated by the Nest CLI. The placeholder version omitted
// AddonsService and crashed Nest's DI on every CI run; supplying an empty
// provider here is enough to satisfy the container without booting Prisma.
describe('AddonsController', () => {
  let controller: AddonsController;

  beforeEach(async () => {
    const module: TestingModule = await Test.createTestingModule({
      controllers: [AddonsController],
      providers: [{ provide: AddonsService, useValue: {} }],
    }).compile();

    controller = module.get<AddonsController>(AddonsController);
  });

  it('should be defined', () => {
    expect(controller).toBeDefined();
  });
});
