// Desi (Indian + Pakistani) Menu Seed Data
// This file contains all menu items for the Desi categories

export const desiCategories = [
  { id: 'BIRYANI', name: 'Biryani', icon: '🍚', color: 'from-amber-600 to-yellow-600' },
  { id: 'KARAHI', name: 'Karahi', icon: '🥘', color: 'from-red-600 to-orange-600' },
  { id: 'BBQ_GRILL', name: 'BBQ & Grill', icon: '🔥', color: 'from-orange-700 to-red-700' },
  { id: 'HANDI', name: 'Handi', icon: '🍲', color: 'from-amber-700 to-orange-700' },
  { id: 'TANDOOR', name: 'Tandoor', icon: '🫓', color: 'from-red-700 to-amber-700' },
  { id: 'CURRIES', name: 'Curries', icon: '🥣', color: 'from-yellow-700 to-amber-600' },
  { id: 'STREET_FOOD', name: 'Street Food', icon: '🌮', color: 'from-green-600 to-teal-600' },
  { id: 'DESI_DESSERT', name: 'Desi Desserts', icon: '🍮', color: 'from-pink-600 to-rose-600' },
  { id: 'DESI_DRINKS', name: 'Desi Drinks', icon: '🧉', color: 'from-emerald-600 to-green-600' },
];

export const desiProducts = [
  // ==================== BIRYANI ====================
  {
    name: 'Chicken Biryani (Half)',
    description: 'Fragrant basmati rice cooked with tender chicken, aromatic spices, and saffron',
    categoryId: 'BIRYANI',
    subcategoryId: 'BIRYANI_CHICKEN',
    basePrice: 12.99,
    prepTimeMinutes: 20,
    kitchenStation: 'GENERAL',
    modifiers: [
      { name: 'Spice Level', options: [{ name: 'Mild', price: 0 }, { name: 'Medium', price: 0 }, { name: 'Spicy', price: 0 }, { name: 'Extra Spicy', price: 0 }] },
      { name: 'Add-ons', options: [{ name: 'Extra Raita', price: 1.99 }, { name: 'Extra Masala', price: 2.99 }, { name: 'Boiled Egg', price: 1.50 }] },
    ],
  },
  {
    name: 'Chicken Biryani (Full)',
    description: 'Full plate of fragrant basmati rice with chicken, serves 2',
    categoryId: 'BIRYANI',
    subcategoryId: 'BIRYANI_CHICKEN',
    basePrice: 22.99,
    prepTimeMinutes: 20,
    kitchenStation: 'GENERAL',
    modifiers: [
      { name: 'Spice Level', options: [{ name: 'Mild', price: 0 }, { name: 'Medium', price: 0 }, { name: 'Spicy', price: 0 }, { name: 'Extra Spicy', price: 0 }] },
      { name: 'Add-ons', options: [{ name: 'Extra Raita', price: 1.99 }, { name: 'Extra Masala', price: 2.99 }, { name: 'Boiled Egg (2)', price: 2.50 }] },
    ],
  },
  {
    name: 'Hyderabadi Chicken Biryani',
    description: 'Authentic Hyderabadi style with dum cooking method',
    categoryId: 'BIRYANI',
    subcategoryId: 'BIRYANI_CHICKEN',
    basePrice: 15.99,
    prepTimeMinutes: 25,
    kitchenStation: 'GENERAL',
    modifiers: [
      { name: 'Spice Level', options: [{ name: 'Mild', price: 0 }, { name: 'Medium', price: 0 }, { name: 'Spicy', price: 0 }] },
    ],
  },
  {
    name: 'Mutton Biryani (Half)',
    description: 'Aromatic basmati rice with tender lamb pieces',
    categoryId: 'BIRYANI',
    subcategoryId: 'BIRYANI_MUTTON',
    basePrice: 15.99,
    prepTimeMinutes: 25,
    kitchenStation: 'GENERAL',
    modifiers: [
      { name: 'Spice Level', options: [{ name: 'Mild', price: 0 }, { name: 'Medium', price: 0 }, { name: 'Spicy', price: 0 }] },
      { name: 'Add-ons', options: [{ name: 'Extra Raita', price: 1.99 }, { name: 'Salad', price: 1.50 }] },
    ],
  },
  {
    name: 'Mutton Biryani (Full)',
    description: 'Full plate of aromatic lamb biryani, serves 2',
    categoryId: 'BIRYANI',
    subcategoryId: 'BIRYANI_MUTTON',
    basePrice: 28.99,
    prepTimeMinutes: 25,
    kitchenStation: 'GENERAL',
    modifiers: [
      { name: 'Spice Level', options: [{ name: 'Mild', price: 0 }, { name: 'Medium', price: 0 }, { name: 'Spicy', price: 0 }] },
    ],
  },
  {
    name: 'Beef Biryani (Half)',
    description: 'Spiced beef chunks with fragrant basmati rice',
    categoryId: 'BIRYANI',
    subcategoryId: 'BIRYANI_BEEF',
    basePrice: 13.99,
    prepTimeMinutes: 20,
    kitchenStation: 'GENERAL',
    modifiers: [
      { name: 'Spice Level', options: [{ name: 'Mild', price: 0 }, { name: 'Medium', price: 0 }, { name: 'Spicy', price: 0 }] },
    ],
  },
  {
    name: 'Vegetable Biryani',
    description: 'Mixed vegetables with fragrant rice and aromatic spices',
    categoryId: 'BIRYANI',
    subcategoryId: 'BIRYANI_VEG',
    basePrice: 10.99,
    prepTimeMinutes: 18,
    kitchenStation: 'GENERAL',
    modifiers: [
      { name: 'Spice Level', options: [{ name: 'Mild', price: 0 }, { name: 'Medium', price: 0 }, { name: 'Spicy', price: 0 }] },
      { name: 'Add Paneer', options: [{ name: 'Add Paneer Cubes', price: 3.99 }] },
    ],
  },
  {
    name: 'Special Shahi Biryani',
    description: 'Chef\'s special recipe with premium ingredients and saffron',
    categoryId: 'BIRYANI',
    subcategoryId: 'BIRYANI_SPECIAL',
    basePrice: 18.99,
    prepTimeMinutes: 30,
    kitchenStation: 'GENERAL',
    modifiers: [
      { name: 'Protein', options: [{ name: 'Chicken', price: 0 }, { name: 'Mutton', price: 4.00 }, { name: 'Mix', price: 3.00 }] },
    ],
  },
  {
    name: 'Egg Biryani',
    description: 'Fragrant rice with boiled eggs and spices',
    categoryId: 'BIRYANI',
    subcategoryId: 'BIRYANI_VEG',
    basePrice: 11.99,
    prepTimeMinutes: 18,
    kitchenStation: 'GENERAL',
    modifiers: [
      { name: 'Extra Eggs', options: [{ name: '+1 Egg', price: 1.50 }, { name: '+2 Eggs', price: 2.50 }] },
    ],
  },
  {
    name: 'Biryani Family Pack',
    description: 'Serves 4-5 people with choice of protein',
    categoryId: 'BIRYANI',
    subcategoryId: 'BIRYANI_SPECIAL',
    basePrice: 45.99,
    prepTimeMinutes: 35,
    kitchenStation: 'GENERAL',
    modifiers: [
      { name: 'Protein', options: [{ name: 'Chicken', price: 0 }, { name: 'Mutton', price: 10.00 }, { name: 'Beef', price: 5.00 }, { name: 'Mixed', price: 8.00 }] },
    ],
  },

  // ==================== KARAHI ====================
  {
    name: 'Chicken Karahi (Half)',
    description: 'Traditional wok-cooked chicken with tomatoes, ginger, and green chilies',
    categoryId: 'KARAHI',
    subcategoryId: 'KARAHI_CHICKEN',
    basePrice: 14.99,
    prepTimeMinutes: 20,
    kitchenStation: 'GENERAL',
    modifiers: [
      { name: 'Spice Level', options: [{ name: 'Mild', price: 0 }, { name: 'Medium', price: 0 }, { name: 'Spicy', price: 0 }] },
      { name: 'Add-ons', options: [{ name: 'Extra Naan', price: 1.99 }, { name: 'Raita', price: 1.99 }, { name: 'Extra Ginger', price: 0.99 }] },
    ],
  },
  {
    name: 'Chicken Karahi (Full)',
    description: 'Full karahi with chicken, serves 3-4',
    categoryId: 'KARAHI',
    subcategoryId: 'KARAHI_CHICKEN',
    basePrice: 26.99,
    prepTimeMinutes: 25,
    kitchenStation: 'GENERAL',
    modifiers: [
      { name: 'Spice Level', options: [{ name: 'Mild', price: 0 }, { name: 'Medium', price: 0 }, { name: 'Spicy', price: 0 }] },
    ],
  },
  {
    name: 'Mutton Karahi (Half)',
    description: 'Classic lamb karahi with traditional spices',
    categoryId: 'KARAHI',
    subcategoryId: 'KARAHI_MUTTON',
    basePrice: 18.99,
    prepTimeMinutes: 25,
    kitchenStation: 'GENERAL',
    modifiers: [
      { name: 'Spice Level', options: [{ name: 'Mild', price: 0 }, { name: 'Medium', price: 0 }, { name: 'Spicy', price: 0 }] },
    ],
  },
  {
    name: 'Mutton Karahi (Full)',
    description: 'Full lamb karahi, serves 3-4',
    categoryId: 'KARAHI',
    subcategoryId: 'KARAHI_MUTTON',
    basePrice: 34.99,
    prepTimeMinutes: 30,
    kitchenStation: 'GENERAL',
    modifiers: [
      { name: 'Spice Level', options: [{ name: 'Mild', price: 0 }, { name: 'Medium', price: 0 }, { name: 'Spicy', price: 0 }] },
    ],
  },
  {
    name: 'Beef Karahi',
    description: 'Spicy beef karahi with special masala',
    categoryId: 'KARAHI',
    subcategoryId: 'KARAHI_BEEF',
    basePrice: 16.99,
    prepTimeMinutes: 22,
    kitchenStation: 'GENERAL',
    modifiers: [
      { name: 'Spice Level', options: [{ name: 'Mild', price: 0 }, { name: 'Medium', price: 0 }, { name: 'Spicy', price: 0 }] },
    ],
  },
  {
    name: 'Prawn Karahi',
    description: 'Fresh prawns cooked in karahi masala',
    categoryId: 'KARAHI',
    subcategoryId: 'KARAHI_PRAWN',
    basePrice: 19.99,
    prepTimeMinutes: 20,
    kitchenStation: 'GENERAL',
    modifiers: [
      { name: 'Spice Level', options: [{ name: 'Mild', price: 0 }, { name: 'Medium', price: 0 }, { name: 'Spicy', price: 0 }] },
    ],
  },
  {
    name: 'Paneer Karahi',
    description: 'Cottage cheese in rich tomato gravy',
    categoryId: 'KARAHI',
    subcategoryId: 'KARAHI_PANEER',
    basePrice: 13.99,
    prepTimeMinutes: 18,
    kitchenStation: 'GENERAL',
    modifiers: [
      { name: 'Spice Level', options: [{ name: 'Mild', price: 0 }, { name: 'Medium', price: 0 }] },
      { name: 'Extra Paneer', options: [{ name: 'Double Paneer', price: 4.99 }] },
    ],
  },
  {
    name: 'White Chicken Karahi',
    description: 'Creamy white karahi with yogurt and cream',
    categoryId: 'KARAHI',
    subcategoryId: 'KARAHI_CHICKEN',
    basePrice: 16.99,
    prepTimeMinutes: 22,
    kitchenStation: 'GENERAL',
    modifiers: [
      { name: 'Cream Level', options: [{ name: 'Regular', price: 0 }, { name: 'Extra Creamy', price: 1.99 }] },
    ],
  },
  {
    name: 'Green Chicken Karahi',
    description: 'Karahi with fresh green herbs and chilies',
    categoryId: 'KARAHI',
    subcategoryId: 'KARAHI_CHICKEN',
    basePrice: 15.99,
    prepTimeMinutes: 20,
    kitchenStation: 'GENERAL',
    modifiers: [
      { name: 'Spice Level', options: [{ name: 'Medium', price: 0 }, { name: 'Spicy', price: 0 }, { name: 'Extra Spicy', price: 0 }] },
    ],
  },

  // ==================== BBQ & GRILL ====================
  {
    name: 'Chicken Tikka (4 pcs)',
    description: 'Boneless chicken marinated in yogurt and spices, grilled to perfection',
    categoryId: 'BBQ_GRILL',
    subcategoryId: 'BBQ_TIKKA',
    basePrice: 12.99,
    prepTimeMinutes: 20,
    kitchenStation: 'GRILL',
    modifiers: [
      { name: 'Spice Level', options: [{ name: 'Mild', price: 0 }, { name: 'Medium', price: 0 }, { name: 'Spicy', price: 0 }] },
      { name: 'Add-ons', options: [{ name: 'Extra Chutney', price: 0.99 }, { name: 'Onion Rings', price: 1.50 }] },
    ],
  },
  {
    name: 'Chicken Tikka (8 pcs)',
    description: 'Full portion of grilled chicken tikka',
    categoryId: 'BBQ_GRILL',
    subcategoryId: 'BBQ_TIKKA',
    basePrice: 22.99,
    prepTimeMinutes: 25,
    kitchenStation: 'GRILL',
    modifiers: [
      { name: 'Spice Level', options: [{ name: 'Mild', price: 0 }, { name: 'Medium', price: 0 }, { name: 'Spicy', price: 0 }] },
    ],
  },
  {
    name: 'Seekh Kebab (4 pcs)',
    description: 'Minced beef skewers with aromatic spices',
    categoryId: 'BBQ_GRILL',
    subcategoryId: 'BBQ_SEEKH',
    basePrice: 11.99,
    prepTimeMinutes: 18,
    kitchenStation: 'GRILL',
    modifiers: [
      { name: 'Meat Type', options: [{ name: 'Beef', price: 0 }, { name: 'Chicken', price: 0 }, { name: 'Mutton', price: 3.00 }] },
    ],
  },
  {
    name: 'Boti Kebab',
    description: 'Tender chunks of meat marinated and grilled',
    categoryId: 'BBQ_GRILL',
    subcategoryId: 'BBQ_BOTI',
    basePrice: 14.99,
    prepTimeMinutes: 20,
    kitchenStation: 'GRILL',
    modifiers: [
      { name: 'Meat', options: [{ name: 'Beef', price: 0 }, { name: 'Mutton', price: 4.00 }] },
    ],
  },
  {
    name: 'Malai Boti',
    description: 'Creamy marinated meat chunks with mild spices',
    categoryId: 'BBQ_GRILL',
    subcategoryId: 'BBQ_MALAI',
    basePrice: 13.99,
    prepTimeMinutes: 20,
    kitchenStation: 'GRILL',
    modifiers: [
      { name: 'Meat', options: [{ name: 'Chicken', price: 0 }, { name: 'Beef', price: 1.00 }] },
    ],
  },
  {
    name: 'BBQ Wings (6 pcs)',
    description: 'Desi-style grilled wings with special marinade',
    categoryId: 'BBQ_GRILL',
    subcategoryId: 'BBQ_WINGS',
    basePrice: 9.99,
    prepTimeMinutes: 18,
    kitchenStation: 'GRILL',
    modifiers: [
      { name: 'Flavor', options: [{ name: 'Classic', price: 0 }, { name: 'Spicy', price: 0 }, { name: 'Honey Glaze', price: 0.99 }] },
    ],
  },
  {
    name: 'Reshmi Kebab',
    description: 'Silky smooth minced chicken kebabs',
    categoryId: 'BBQ_GRILL',
    subcategoryId: 'BBQ_SEEKH',
    basePrice: 12.99,
    prepTimeMinutes: 18,
    kitchenStation: 'GRILL',
    modifiers: [],
  },
  {
    name: 'BBQ Platter',
    description: 'Assorted BBQ items: 2 tikka, 2 seekh, 2 malai boti',
    categoryId: 'BBQ_GRILL',
    subcategoryId: 'BBQ_TIKKA',
    basePrice: 24.99,
    prepTimeMinutes: 25,
    kitchenStation: 'GRILL',
    modifiers: [
      { name: 'Spice Level', options: [{ name: 'Mild', price: 0 }, { name: 'Medium', price: 0 }, { name: 'Spicy', price: 0 }] },
    ],
  },
  {
    name: 'Grilled Fish',
    description: 'Whole fish marinated in desi spices and grilled',
    categoryId: 'BBQ_GRILL',
    subcategoryId: 'BBQ_TIKKA',
    basePrice: 18.99,
    prepTimeMinutes: 25,
    kitchenStation: 'GRILL',
    modifiers: [
      { name: 'Fish Type', options: [{ name: 'Tilapia', price: 0 }, { name: 'Salmon', price: 5.00 }] },
    ],
  },

  // ==================== HANDI ====================
  {
    name: 'Chicken Handi',
    description: 'Creamy clay pot chicken with rich gravy',
    categoryId: 'HANDI',
    subcategoryId: 'HANDI_CHICKEN',
    basePrice: 15.99,
    prepTimeMinutes: 22,
    kitchenStation: 'GENERAL',
    modifiers: [
      { name: 'Spice Level', options: [{ name: 'Mild', price: 0 }, { name: 'Medium', price: 0 }, { name: 'Spicy', price: 0 }] },
      { name: 'Extras', options: [{ name: 'Extra Cream', price: 1.99 }, { name: 'Extra Butter', price: 1.50 }] },
    ],
  },
  {
    name: 'Mutton Handi',
    description: 'Slow-cooked lamb in clay pot with aromatic spices',
    categoryId: 'HANDI',
    subcategoryId: 'HANDI_MUTTON',
    basePrice: 19.99,
    prepTimeMinutes: 28,
    kitchenStation: 'GENERAL',
    modifiers: [
      { name: 'Spice Level', options: [{ name: 'Mild', price: 0 }, { name: 'Medium', price: 0 }, { name: 'Spicy', price: 0 }] },
    ],
  },
  {
    name: 'Butter Chicken Handi',
    description: 'Rich makhani gravy with tender chicken pieces',
    categoryId: 'HANDI',
    subcategoryId: 'HANDI_MAKHNI',
    basePrice: 16.99,
    prepTimeMinutes: 22,
    kitchenStation: 'GENERAL',
    modifiers: [
      { name: 'Butter Level', options: [{ name: 'Regular', price: 0 }, { name: 'Extra Butter', price: 1.99 }] },
    ],
  },
  {
    name: 'Paneer Handi',
    description: 'Cottage cheese in creamy tomato gravy',
    categoryId: 'HANDI',
    subcategoryId: 'HANDI_PANEER',
    basePrice: 14.99,
    prepTimeMinutes: 20,
    kitchenStation: 'GENERAL',
    modifiers: [
      { name: 'Extras', options: [{ name: 'Extra Paneer', price: 3.99 }, { name: 'Extra Cream', price: 1.99 }] },
    ],
  },
  {
    name: 'Special Handi',
    description: 'Chef\'s special recipe with mixed meat',
    categoryId: 'HANDI',
    subcategoryId: 'HANDI_CHICKEN',
    basePrice: 21.99,
    prepTimeMinutes: 25,
    kitchenStation: 'GENERAL',
    modifiers: [],
  },
  {
    name: 'Handi Combo',
    description: 'Choice of handi with naan and raita',
    categoryId: 'HANDI',
    subcategoryId: 'HANDI_CHICKEN',
    basePrice: 18.99,
    prepTimeMinutes: 25,
    kitchenStation: 'GENERAL',
    modifiers: [
      { name: 'Handi Type', options: [{ name: 'Chicken', price: 0 }, { name: 'Mutton', price: 4.00 }, { name: 'Paneer', price: -1.00 }] },
    ],
  },

  // ==================== TANDOOR ====================
  {
    name: 'Plain Naan',
    description: 'Freshly baked tandoori naan',
    categoryId: 'TANDOOR',
    subcategoryId: 'TANDOOR_NAAN',
    basePrice: 1.99,
    prepTimeMinutes: 5,
    kitchenStation: 'GENERAL',
    modifiers: [
      { name: 'Quantity', options: [{ name: '1 Piece', price: 0 }, { name: '2 Pieces', price: 1.99 }, { name: '4 Pieces', price: 3.99 }] },
      { name: 'Butter', options: [{ name: 'Plain', price: 0 }, { name: 'Butter Naan', price: 0.50 }] },
    ],
  },
  {
    name: 'Garlic Naan',
    description: 'Naan topped with fresh garlic and cilantro',
    categoryId: 'TANDOOR',
    subcategoryId: 'TANDOOR_NAAN',
    basePrice: 2.99,
    prepTimeMinutes: 5,
    kitchenStation: 'GENERAL',
    modifiers: [
      { name: 'Extras', options: [{ name: 'Extra Garlic', price: 0.50 }, { name: 'Cheese', price: 1.99 }] },
    ],
  },
  {
    name: 'Cheese Naan',
    description: 'Naan stuffed with melted cheese',
    categoryId: 'TANDOOR',
    subcategoryId: 'TANDOOR_NAAN',
    basePrice: 3.99,
    prepTimeMinutes: 6,
    kitchenStation: 'GENERAL',
    modifiers: [],
  },
  {
    name: 'Tandoori Roti',
    description: 'Whole wheat flatbread baked in tandoor',
    categoryId: 'TANDOOR',
    subcategoryId: 'TANDOOR_ROT',
    basePrice: 1.49,
    prepTimeMinutes: 4,
    kitchenStation: 'GENERAL',
    modifiers: [
      { name: 'Quantity', options: [{ name: '1 Piece', price: 0 }, { name: '2 Pieces', price: 1.49 }, { name: '4 Pieces', price: 2.99 }] },
    ],
  },
  {
    name: 'Aloo Paratha',
    description: 'Flatbread stuffed with spiced potatoes',
    categoryId: 'TANDOOR',
    subcategoryId: 'TANDOOR_PARATHA',
    basePrice: 3.99,
    prepTimeMinutes: 8,
    kitchenStation: 'GENERAL',
    modifiers: [
      { name: 'Extras', options: [{ name: 'Extra Butter', price: 0.50 }, { name: 'Yogurt', price: 0.99 }] },
    ],
  },
  {
    name: 'Paneer Paratha',
    description: 'Flatbread stuffed with cottage cheese',
    categoryId: 'TANDOOR',
    subcategoryId: 'TANDOOR_PARATHA',
    basePrice: 4.99,
    prepTimeMinutes: 8,
    kitchenStation: 'GENERAL',
    modifiers: [],
  },
  {
    name: 'Kulcha',
    description: 'Leavened bread stuffed with seasoned potatoes',
    categoryId: 'TANDOOR',
    subcategoryId: 'TANDOOR_KULCHA',
    basePrice: 3.49,
    prepTimeMinutes: 7,
    kitchenStation: 'GENERAL',
    modifiers: [
      { name: 'Stuffing', options: [{ name: 'Aloo', price: 0 }, { name: 'Onion', price: 0 }, { name: 'Paneer', price: 1.50 }] },
    ],
  },
  {
    name: 'Lachha Paratha',
    description: 'Flaky layered paratha',
    categoryId: 'TANDOOR',
    subcategoryId: 'TANDOOR_LACCHA',
    basePrice: 2.99,
    prepTimeMinutes: 6,
    kitchenStation: 'GENERAL',
    modifiers: [],
  },
  {
    name: 'Tandoori Bread Basket',
    description: 'Assorted breads: 2 naan, 2 roti, 1 paratha',
    categoryId: 'TANDOOR',
    subcategoryId: 'TANDOOR_NAAN',
    basePrice: 8.99,
    prepTimeMinutes: 10,
    kitchenStation: 'GENERAL',
    modifiers: [],
  },

  // ==================== CURRIES ====================
  {
    name: 'Chicken Korma',
    description: 'Mild creamy curry with yogurt and nuts',
    categoryId: 'CURRIES',
    subcategoryId: 'CURRY_KORMA',
    basePrice: 14.99,
    prepTimeMinutes: 20,
    kitchenStation: 'GENERAL',
    modifiers: [
      { name: 'Spice Level', options: [{ name: 'Mild', price: 0 }, { name: 'Medium', price: 0 }] },
    ],
  },
  {
    name: 'Mutton Korma',
    description: 'Rich lamb curry with cream and spices',
    categoryId: 'CURRIES',
    subcategoryId: 'CURRY_KORMA',
    basePrice: 18.99,
    prepTimeMinutes: 25,
    kitchenStation: 'GENERAL',
    modifiers: [],
  },
  {
    name: 'Chicken Tikka Masala',
    description: 'Grilled chicken in spiced tomato gravy',
    categoryId: 'CURRIES',
    subcategoryId: 'CURRY_MASALA',
    basePrice: 15.99,
    prepTimeMinutes: 22,
    kitchenStation: 'GENERAL',
    modifiers: [
      { name: 'Spice Level', options: [{ name: 'Mild', price: 0 }, { name: 'Medium', price: 0 }, { name: 'Spicy', price: 0 }] },
    ],
  },
  {
    name: 'Chicken Vindaloo',
    description: 'Hot and tangy curry with vinegar',
    categoryId: 'CURRIES',
    subcategoryId: 'CURRY_VINDALOO',
    basePrice: 15.99,
    prepTimeMinutes: 22,
    kitchenStation: 'GENERAL',
    modifiers: [
      { name: 'Spice Level', options: [{ name: 'Spicy', price: 0 }, { name: 'Extra Spicy', price: 0 }] },
    ],
  },
  {
    name: 'Saag Chicken',
    description: 'Chicken with spinach and mustard greens',
    categoryId: 'CURRIES',
    subcategoryId: 'CURRY_SAAG',
    basePrice: 14.99,
    prepTimeMinutes: 20,
    kitchenStation: 'GENERAL',
    modifiers: [],
  },
  {
    name: 'Palak Paneer',
    description: 'Cottage cheese in creamy spinach gravy',
    categoryId: 'CURRIES',
    subcategoryId: 'CURRY_SAAG',
    basePrice: 13.99,
    prepTimeMinutes: 20,
    kitchenStation: 'GENERAL',
    modifiers: [
      { name: 'Extras', options: [{ name: 'Extra Paneer', price: 3.99 }] },
    ],
  },
  {
    name: 'Daal Makhani',
    description: 'Creamy black lentils slow-cooked',
    categoryId: 'CURRIES',
    subcategoryId: 'CURRY_DAAL',
    basePrice: 10.99,
    prepTimeMinutes: 18,
    kitchenStation: 'GENERAL',
    modifiers: [
      { name: 'Extras', options: [{ name: 'Extra Cream', price: 0.99 }, { name: 'Extra Butter', price: 0.99 }] },
    ],
  },
  {
    name: 'Yellow Daal',
    description: 'Yellow lentils tempered with spices',
    categoryId: 'CURRIES',
    subcategoryId: 'CURRY_DAAL',
    basePrice: 9.99,
    prepTimeMinutes: 15,
    kitchenStation: 'GENERAL',
    modifiers: [],
  },
  {
    name: 'Chana Masala',
    description: 'Chickpeas in spicy tomato gravy',
    categoryId: 'CURRIES',
    subcategoryId: 'CURRY_MASALA',
    basePrice: 10.99,
    prepTimeMinutes: 18,
    kitchenStation: 'GENERAL',
    modifiers: [
      { name: 'Spice Level', options: [{ name: 'Mild', price: 0 }, { name: 'Medium', price: 0 }, { name: 'Spicy', price: 0 }] },
    ],
  },

  // ==================== STREET FOOD ====================
  {
    name: 'Vegetable Samosa (2 pcs)',
    description: 'Crispy pastry filled with spiced potatoes and peas',
    categoryId: 'STREET_FOOD',
    subcategoryId: 'STREET_SAMOSA',
    basePrice: 4.99,
    prepTimeMinutes: 10,
    kitchenStation: 'FRYER',
    modifiers: [
      { name: 'Chutney', options: [{ name: 'Tamarind', price: 0 }, { name: 'Mint', price: 0 }, { name: 'Both', price: 0 }] },
    ],
  },
  {
    name: 'Chicken Samosa (2 pcs)',
    description: 'Crispy pastry with spiced chicken filling',
    categoryId: 'STREET_FOOD',
    subcategoryId: 'STREET_SAMOSA',
    basePrice: 5.99,
    prepTimeMinutes: 10,
    kitchenStation: 'FRYER',
    modifiers: [],
  },
  {
    name: 'Chicken Kathi Roll',
    description: 'Wrap with grilled chicken, onions, and chutney',
    categoryId: 'STREET_FOOD',
    subcategoryId: 'STREET_ROLL',
    basePrice: 8.99,
    prepTimeMinutes: 12,
    kitchenStation: 'GENERAL',
    modifiers: [
      { name: 'Spice Level', options: [{ name: 'Mild', price: 0 }, { name: 'Medium', price: 0 }, { name: 'Spicy', price: 0 }] },
      { name: 'Extras', options: [{ name: 'Extra Chicken', price: 2.99 }, { name: 'Cheese', price: 1.50 }] },
    ],
  },
  {
    name: 'Veg Kathi Roll',
    description: 'Wrap with paneer, vegetables, and chutney',
    categoryId: 'STREET_FOOD',
    subcategoryId: 'STREET_ROLL',
    basePrice: 7.99,
    prepTimeMinutes: 10,
    kitchenStation: 'GENERAL',
    modifiers: [],
  },
  {
    name: 'Aloo Chaat',
    description: 'Spiced potato chaat with chutneys',
    categoryId: 'STREET_FOOD',
    subcategoryId: 'STREET_CHAAT',
    basePrice: 5.99,
    prepTimeMinutes: 8,
    kitchenStation: 'GENERAL',
    modifiers: [
      { name: 'Spice Level', options: [{ name: 'Mild', price: 0 }, { name: 'Medium', price: 0 }, { name: 'Spicy', price: 0 }] },
    ],
  },
  {
    name: 'Samosa Chaat',
    description: 'Crushed samosa with chutneys and yogurt',
    categoryId: 'STREET_FOOD',
    subcategoryId: 'STREET_CHAAT',
    basePrice: 6.99,
    prepTimeMinutes: 8,
    kitchenStation: 'GENERAL',
    modifiers: [],
  },
  {
    name: 'Vegetable Pakora',
    description: 'Mixed vegetable fritters (8 pcs)',
    categoryId: 'STREET_FOOD',
    subcategoryId: 'STREET_PAKORA',
    basePrice: 5.99,
    prepTimeMinutes: 10,
    kitchenStation: 'FRYER',
    modifiers: [
      { name: 'Chutney', options: [{ name: 'Tamarind', price: 0 }, { name: 'Mint', price: 0 }] },
    ],
  },
  {
    name: 'Chicken Pakora',
    description: 'Chicken fritters with spices (6 pcs)',
    categoryId: 'STREET_FOOD',
    subcategoryId: 'STREET_PAKORA',
    basePrice: 7.99,
    prepTimeMinutes: 12,
    kitchenStation: 'FRYER',
    modifiers: [],
  },
  {
    name: 'Gol Gappa (8 pcs)',
    description: 'Crispy shells filled with spiced water and potatoes',
    categoryId: 'STREET_FOOD',
    subcategoryId: 'STREET_GOLGAPPA',
    basePrice: 6.99,
    prepTimeMinutes: 8,
    kitchenStation: 'GENERAL',
    modifiers: [
      { name: 'Water Type', options: [{ name: 'Regular', price: 0 }, { name: 'Sweet', price: 0 }, { name: 'Mixed', price: 0 }] },
    ],
  },
  {
    name: 'Dahi Bhalla',
    description: 'Lentil dumplings in yogurt with chutneys',
    categoryId: 'STREET_FOOD',
    subcategoryId: 'STREET_CHAAT',
    basePrice: 6.99,
    prepTimeMinutes: 8,
    kitchenStation: 'GENERAL',
    modifiers: [],
  },

  // ==================== DESI DESSERTS ====================
  {
    name: 'Gulab Jamun (2 pcs)',
    description: 'Soft milk dumplings in sugar syrup',
    categoryId: 'DESI_DESSERT',
    subcategoryId: 'DESERT_GULAB',
    basePrice: 4.99,
    prepTimeMinutes: 5,
    kitchenStation: 'DESSERT',
    modifiers: [
      { name: 'Quantity', options: [{ name: '2 pcs', price: 0 }, { name: '4 pcs', price: 3.99 }] },
      { name: 'Extras', options: [{ name: 'Extra Syrup', price: 0.50 }, { name: 'Ice Cream', price: 1.99 }] },
    ],
  },
  {
    name: 'Hot Jalebi (5 oz)',
    description: 'Crispy spirals soaked in sugar syrup',
    categoryId: 'DESI_DESSERT',
    subcategoryId: 'DESERT_JALEBI',
    basePrice: 5.99,
    prepTimeMinutes: 8,
    kitchenStation: 'DESSERT',
    modifiers: [
      { name: 'Extras', options: [{ name: 'Rabri', price: 2.99 }] },
    ],
  },
  {
    name: 'Kheer',
    description: 'Creamy rice pudding with cardamom and nuts',
    categoryId: 'DESI_DESSERT',
    subcategoryId: 'DESERT_KHEER',
    basePrice: 5.99,
    prepTimeMinutes: 5,
    kitchenStation: 'DESSERT',
    modifiers: [
      { name: 'Temperature', options: [{ name: 'Hot', price: 0 }, { name: 'Cold', price: 0 }] },
    ],
  },
  {
    name: 'Gajar ka Halwa',
    description: 'Carrot pudding with ghee and nuts',
    categoryId: 'DESI_DESSERT',
    subcategoryId: 'DESERT_HALWA',
    basePrice: 6.99,
    prepTimeMinutes: 5,
    kitchenStation: 'DESSERT',
    modifiers: [
      { name: 'Extras', options: [{ name: 'Extra Nuts', price: 1.00 }, { name: 'Ice Cream', price: 1.99 }] },
    ],
  },
  {
    name: 'Kulfi',
    description: 'Traditional Indian ice cream',
    categoryId: 'DESI_DESSERT',
    subcategoryId: 'DESERT_KULFI',
    basePrice: 4.99,
    prepTimeMinutes: 2,
    kitchenStation: 'DESSERT',
    modifiers: [
      { name: 'Flavor', options: [{ name: 'Mango', price: 0 }, { name: 'Pista', price: 0 }, { name: 'Malai', price: 0 }, { name: 'Rose', price: 0 }] },
    ],
  },
  {
    name: 'Rasmalai (2 pcs)',
    description: 'Soft cheese patties in saffron milk',
    categoryId: 'DESI_DESSERT',
    subcategoryId: 'DESERT_RASMALAI',
    basePrice: 5.99,
    prepTimeMinutes: 5,
    kitchenStation: 'DESSERT',
    modifiers: [],
  },
  {
    name: 'Zarda',
    description: 'Sweet yellow rice with nuts and raisins',
    categoryId: 'DESI_DESSERT',
    subcategoryId: 'DESERT_KHEER',
    basePrice: 5.99,
    prepTimeMinutes: 5,
    kitchenStation: 'DESSERT',
    modifiers: [],
  },
  {
    name: 'Desert Platter',
    description: 'Assorted desserts: 2 gulab jamun, 1 kulfi, kheer',
    categoryId: 'DESI_DESSERT',
    subcategoryId: 'DESERT_GULAB',
    basePrice: 12.99,
    prepTimeMinutes: 5,
    kitchenStation: 'DESSERT',
    modifiers: [
      { name: 'Kulfi Flavor', options: [{ name: 'Mango', price: 0 }, { name: 'Pista', price: 0 }, { name: 'Malai', price: 0 }] },
    ],
  },

  // ==================== DESI DRINKS ====================
  {
    name: 'Sweet Lassi',
    description: 'Refreshing yogurt drink sweetened with sugar',
    categoryId: 'DESI_DRINKS',
    subcategoryId: 'DRINK_LASSI',
    basePrice: 3.99,
    prepTimeMinutes: 3,
    kitchenStation: 'DRINKS',
    modifiers: [
      { name: 'Size', options: [{ name: 'Regular', price: 0 }, { name: 'Large', price: 1.50 }] },
    ],
  },
  {
    name: 'Salted Lassi',
    description: 'Savory yogurt drink with spices',
    categoryId: 'DESI_DRINKS',
    subcategoryId: 'DRINK_LASSI',
    basePrice: 3.99,
    prepTimeMinutes: 3,
    kitchenStation: 'DRINKS',
    modifiers: [],
  },
  {
    name: 'Mango Lassi',
    description: 'Creamy yogurt drink with mango pulp',
    categoryId: 'DESI_DRINKS',
    subcategoryId: 'DRINK_LASSI',
    basePrice: 4.99,
    prepTimeMinutes: 3,
    kitchenStation: 'DRINKS',
    modifiers: [
      { name: 'Size', options: [{ name: 'Regular', price: 0 }, { name: 'Large', price: 1.50 }] },
    ],
  },
  {
    name: 'Strawberry Lassi',
    description: 'Yogurt drink with fresh strawberry',
    categoryId: 'DESI_DRINKS',
    subcategoryId: 'DRINK_LASSI',
    basePrice: 4.99,
    prepTimeMinutes: 3,
    kitchenStation: 'DRINKS',
    modifiers: [],
  },
  {
    name: 'Masala Chai',
    description: 'Spiced tea with milk',
    categoryId: 'DESI_DRINKS',
    subcategoryId: 'DRINK_CHAI',
    basePrice: 2.99,
    prepTimeMinutes: 5,
    kitchenStation: 'DRINKS',
    modifiers: [
      { name: 'Size', options: [{ name: 'Regular', price: 0 }, { name: 'Large', price: 1.00 }] },
      { name: 'Strength', options: [{ name: 'Regular', price: 0 }, { name: 'Strong', price: 0 }] },
    ],
  },
  {
    name: 'Green Tea',
    description: 'Hot green tea with cardamom',
    categoryId: 'DESI_DRINKS',
    subcategoryId: 'DRINK_CHAI',
    basePrice: 2.49,
    prepTimeMinutes: 4,
    kitchenStation: 'DRINKS',
    modifiers: [],
  },
  {
    name: 'Rooh Afza',
    description: 'Rose syrup drink with water or milk',
    categoryId: 'DESI_DRINKS',
    subcategoryId: 'DRINK_ROOH',
    basePrice: 3.49,
    prepTimeMinutes: 2,
    kitchenStation: 'DRINKS',
    modifiers: [
      { name: 'Base', options: [{ name: 'Water', price: 0 }, { name: 'Milk', price: 0.50 }] },
      { name: 'With Basil Seeds', options: [{ name: 'Yes', price: 0.50 }, { name: 'No', price: 0 }] },
    ],
  },
  {
    name: 'Nimboo Pani',
    description: 'Refreshing lemon water with spices',
    categoryId: 'DESI_DRINKS',
    subcategoryId: 'DRINK_NIMBOO',
    basePrice: 2.99,
    prepTimeMinutes: 2,
    kitchenStation: 'DRINKS',
    modifiers: [
      { name: 'Style', options: [{ name: 'Sweet', price: 0 }, { name: 'Salted', price: 0 }, { name: 'Mixed', price: 0 }] },
    ],
  },
  {
    name: 'Thandai',
    description: 'Cooling milk drink with nuts and spices',
    categoryId: 'DESI_DRINKS',
    subcategoryId: 'DRINK_THANDAI',
    basePrice: 4.99,
    prepTimeMinutes: 3,
    kitchenStation: 'DRINKS',
    modifiers: [],
  },
  {
    name: 'Shikanjvi',
    description: 'Spiced lemonade',
    categoryId: 'DESI_DRINKS',
    subcategoryId: 'DRINK_NIMBOO',
    basePrice: 2.99,
    prepTimeMinutes: 2,
    kitchenStation: 'DRINKS',
    modifiers: [],
  },
  {
    name: 'Fruit Sharbats',
    description: 'Flavored syrup drinks',
    categoryId: 'DESI_DRINKS',
    subcategoryId: 'DRINK_SHARBAT',
    basePrice: 3.49,
    prepTimeMinutes: 2,
    kitchenStation: 'DRINKS',
    modifiers: [
      { name: 'Flavor', options: [{ name: 'Orange', price: 0 }, { name: 'Pineapple', price: 0 }, { name: 'Mango', price: 0 }, { name: 'Blackcurrant', price: 0 }] },
    ],
  },
  {
    name: 'Kashmiri Chai',
    description: 'Pink tea with nuts and cream',
    categoryId: 'DESI_DRINKS',
    subcategoryId: 'DRINK_CHAI',
    basePrice: 3.99,
    prepTimeMinutes: 6,
    kitchenStation: 'DRINKS',
    modifiers: [
      { name: 'Toppings', options: [{ name: 'Regular', price: 0 }, { name: 'Extra Nuts', price: 0.50 }] },
    ],
  },
];

// Function to generate Prisma seed data
export function generateDesiSeedData() {
  return {
    categories: desiCategories,
    products: desiProducts,
  };
}
